name: detectron2-pipeline
channels:
  - conda-forge
  - pytorch
dependencies:
  - python==3.8.18
  - pip
  - numpy
  - tqdm
  - pytest
  - pytorch
  - torchvision
  - cython
  - munkres
  - pillow
  - pip:
    - opencv-contrib-python
    - git+https://github.com/facebookresearch/fvcore@4354c8c09e5dfb22f6e84172d46b7ece24446bc1
    - git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI
